name: Build alphalaneous.pages-api

on:
  push:
    branches:
      - alphalaneous.pages-api 

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false # nevermind
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}
          
  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Fetch Node IDs
      # https://km7dev.tech/cgs-ports/compiled/geode.node-ids.geode
        run: curl https://km7dev.tech/cgs-ports/compiled/geode.node-ids.geode -o build\geode-deps\geode.node-ids.geode

      - name: Build SPECIFICALLY for iOS which is just ridiculous
        uses: geode-catgirls/build-geode-mod@main
        with:
          bindings: geode-catgirls/bindings
          target: iOS
          gh-pat: ${{ secrets.GH_PAT }}
          # super secret
          
  package:
    name: Package and release mod
    runs-on: ubuntu-latest
    needs: ['build', 'build-ios']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build
        name: Combine mods

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
